// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFI-Bk9vP_AOxkg4QpplFCSzhTZP-Drj8',
    appId: '1:1074120253631:web:cdd1b943327d320de8260a',
    messagingSenderId: '1074120253631',
    projectId: 'blackfootapplication',
    authDomain: 'blackfootapplication.firebaseapp.com',
    storageBucket: 'blackfootapplication.appspot.com',
    measurementId: 'G-SWKZTBLM2X',
    databaseURL: "https://blackfootapplication-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWtNigTTsphBJRyVKHVSokmmIJXSzoDpM',
    appId: '1:1074120253631:android:da5b6ef100147513e8260a',
    messagingSenderId: '1074120253631',
    projectId: 'blackfootapplication',
    storageBucket: 'blackfootapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAei5wWfYUnY4morKxRYURRfr_estouU40',
    appId: '1:1074120253631:ios:795628d772cf9384e8260a',
    messagingSenderId: '1074120253631',
    projectId: 'blackfootapplication',
    storageBucket: 'blackfootapplication.appspot.com',
    iosBundleId: 'com.example.okiBlackfoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAei5wWfYUnY4morKxRYURRfr_estouU40',
    appId: '1:1074120253631:ios:82d76001a4fdc859e8260a',
    messagingSenderId: '1074120253631',
    projectId: 'blackfootapplication',
    storageBucket: 'blackfootapplication.appspot.com',
    iosBundleId: 'com.example.okiBlackfoot.RunnerTests',
  );
}
